[package]
name = "image_to_ascii_colored"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
colored = "2"
crossterm = "0.27.0"